### ISSUE TITLE
rewrite EconomyAPI?

### ISSUE THREAD

**Issue by XDqrkneZ** [onebone/downlink#1]
rewrite EconomyAPI? It's mysql provider is worse than yaml provider

**Comment by onebone** [comment]
What do you mean that mysql provider is worse than yaml provider?

**Comment by XDqrkneZ** [comment]
I've been told by sofe, that economyApi doesn't use the advantages of mysql that makes it faster than yaml

**Comment by onebone** [comment]
I didn't get what he meant, I would be pleased if he could give me some extra description for that.

**Comment by onebone** [comment]
You mean this?
https://code.tutsplus.com/tutorials/top-20-mysql-best-practices--net-7855

**Comment by XDqrkneZ** [comment]
does economyapi use those?

**Comment by onebone** [comment]
No, I've only focused on implementing MySQL at that time.
I will work on it when I can overcome tiresomeness setting up development environment on my desktop.
